---
title: "Class 17: Downstream Analysis"
author: "Katherine Quach (A18541014)"
format: pdf
toc: TRUE
---

## Data Import

Import the 4 kallisto files:

```{r}
library(tximport)

# setup the folder and filenames to read
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```

```{r}
head(txi.kallisto$counts)
```

Assigning col and row:

```{r}
colSums(txi.kallisto$counts)
```

```{r}
sum(rowSums(txi.kallisto$counts)>0)
```

Filtering data:

```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
```

```{r}
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```


## PCA

```{r}
pca <- prcomp(t(x), scale=TRUE)
```

```{r}
summary(pca)
```

```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```

Q. Use ggplot to make a similar figure of PC1 vs PC2 and a seperate figure PC1 vs PC3 and PC2 vs PC3.

PC1 vs PC2

```{r}
library(ggplot2)
library(ggrepel)

colData <- data.frame(condition = factor (rep(c("control", "treatment"), each = 2))
row.names = (colData) <- colnames(txi.kallisto$counts)

y <- as.data.frame(pca$x)
y$Condition <- as.factor(colData$condition)

ggplot(y) +
    aes(PC1, PC2, col = Condition) +
  geom_point() +
```

PC1 vs PC3

```{r}
library(ggplot2)
library(ggrepel)

colData <- data.frame(condition = factor (rep(c("control", "treatment"), each = 2))
row.names = (colData) <- colnames(txi.kallisto$counts)

y <- as.data.frame(pca$x)
y$Condition <- as.factor(colData$condition)

ggplot(y) +
    aes(PC1, PC3, col = Condition) +
  geom_point() +
  geom_text_repel(label = rownames (y)) +
  theme_bw()
```


## DESeq

```{r}
library(DESeq2)
```

```{r}
sampleTable <- data.frame(condition = factor(rep(c("control", "treatment"), each = 2)))
rownames(sampleTable) <- colnames(txi.kallisto$counts)
```

```{r}
dds <- DESeqDataSetFromTximport(txi.kallisto,
                                sampleTable, 
                                ~condition)
```

Using counts and average transcript lengths from tximiport

```{r}
dds <- DESeq(dds)
```

```{r}
res <- results(dds)
head(res)
```


## Volcano Plot

```{r}
library(ggplot2)

ggplot(res) +
  aes(log2FoldChange,
      -log(padj)) +
  geom_point() +
  labs(x = "Log 2 Fold Change",
       y = "-log Adjusted P-Value") +
  geom_vline(xintercept = c(-9,9)) +
  goem_hline(yintercept = 0) +
  theme_bw()
```



