---
title: "Class 6: Function Homework"
author: "Katherine Quach (A1854014)"
format: pdf
toc: TRUE
---

## Write a function from the supplied code

```{r}
# Can you improve this analysis code?
library(bio3d)

s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

## Improving the Analysis Code

Initialize bio3d library
```{r}
library(bio3d)
```

Create a reusable function to analyze and plot the analysis of protein drug interactions
```{r}
analyze_protein_bfactors <- function(pdb_id, chain = "A"){
  
  # Read the PDB structure
  pdb <- read.pdb(pdb_id)
  
  # Trim the pdb structure to the selected chain and alpha carbons 
  pdb_trim <- trim.pdb(pdb, chain = chain, elety = "CA")
  
  # Extract the B-factors
  b_factors <- pdb_trim$atom$b
  
  # Plot the B-factors 
  # sse specifies the chain 
  # typ indicates to plot the B-factors as a line plot
  # ylab labels "B-factor" on the y-axis
  # main sets the title for the line plot
  plotb3(b_factors, 
         sse = pdb_trim, 
         typ = "l", 
         ylab = "B-factor", 
         main = paste("B-factor Profile for PDB", pdb_id)
  )
}
# Plotted the B-factor Profiles for Protein Structures
analyze_protein_bfactors("4AKE")
analyze_protein_bfactors("1AKE")
analyze_protein_bfactors("1E4Y")
```

